### ISSUE TITLE
TypeError: call_user_func_array():   Combo to Sqlite to DW error trace

### ISSUE THREAD

**Issue by jkiser99dev** [ComboStrap/combo#113]
Greetings again!

I'm not sure if this sort of thing goes under Issues or Discussions.

A user just reported this dokuwiki error, originating from ComboStrap.  The only thing on 2 pages where this occurs that I see as odd is that they immediately start with: ====topic==== and the missing method is list_open.

ERROR: 
TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Doku_Renderer_metadata does not have a method "list_open"

(Running sqlite3  v3.7.17,  php 8.1)

LOGS:  (fyi - has-motion.com/wiki is a migration testing setup)
2024-06-07 12:47:21	/home/hasmotinc/public_html/wiki/lib/plugins/sqlite/SQLiteDB.php(445)	PDOException: SQLSTATE[HY000]: General error: 1 near "DROP": syntax error
  #0 /home/hasmotinc/public_html/wiki/lib/plugins/sqlite/SQLiteDB.php(445): PDO->exec('ALTER TABLE ali...')
  #1 /home/hasmotinc/public_html/wiki/lib/plugins/sqlite/SQLiteDB.php(83): dokuwiki\plugin\sqlite\SQLiteDB->applyMigrations()
  #2 /home/hasmotinc/public_html/wiki/lib/plugins/data/helper.php(92): dokuwiki\plugin\sqlite\SQLiteDB->__construct('data', '/home/hasmotinc...')
  #3 /home/hasmotinc/public_html/wiki/lib/plugins/data/action.php(57): helper_plugin_data->getDB()
  #4 /home/hasmotinc/public_html/wiki/inc/Extension/EventHandler.php(80): action_plugin_data->handle(Object(dokuwiki\Extension\Event), NULL)
  #5 /home/hasmotinc/public_html/wiki/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
  #6 /home/hasmotinc/public_html/wiki/inc/Extension/Event.php(133): dokuwiki\Extension\Event->advise_before(false)
  #7 /home/hasmotinc/public_html/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger('_io_writeWikiPa...', false)
  #8 /home/hasmotinc/public_html/wiki/inc/io.php(217): dokuwiki\Extension\Event::createAndTrigger('IO_WIKIPAGE_WRI...', Array, '_io_writeWikiPa...', false)
  #9 /home/hasmotinc/public_html/wiki/inc/File/PageFile.php(276): io_writeWikiPage('/home/hasmotinc...', '**HAS-Motion, I...', 'start', 1717764441)
  #10 /home/hasmotinc/public_html/wiki/inc/File/PageFile.php(189): dokuwiki\File\PageFile->saveOldRevision()
  #11 /home/hasmotinc/public_html/wiki/inc/common.php(1300): dokuwiki\File\PageFile->saveWikiText('**HAS-Motion, I...', 'Ensured that Vi...', true)
  #12 /home/hasmotinc/public_html/wiki/inc/Action/Save.php(58): saveWikiText('start', '**HAS-Motion, I...', 'Ensured that Vi...', true)
  #13 /home/hasmotinc/public_html/wiki/inc/ActionRouter.php(86): dokuwiki\Action\Save->preProcess()
  #14 /home/hasmotinc/public_html/wiki/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction('save')
  #15 /home/hasmotinc/public_html/wiki/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
  #16 /home/hasmotinc/public_html/wiki/inc/actions.php(19): dokuwiki\ActionRouter::getInstance(true)
  #17 /home/hasmotinc/public_html/wiki/doku.php(131): act_dispatch()
  #18 {main}

2024-06-07 12:50:17	/home/hasmotinc/public_html/wiki/lib/plugins/combo/ComboStrap/EditButton.php(269)	E_WARNING: Undefined array key "name"
  #0 /home/hasmotinc/public_html/wiki/lib/plugins/combo/ComboStrap/EditButton.php(269): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/hasmotinc...', 269)
  #1 [internal function]: ComboStrap\EditButton::ComboStrap\{closure}(Array)
  #2 /home/hasmotinc/public_html/wiki/lib/plugins/combo/ComboStrap/EditButton.php(332): preg_replace_callback('/<!--\\s*EDIT({....', Object(Closure), '<section class=...')
  #3 /home/hasmotinc/public_html/wiki/lib/plugins/combo/ComboStrap/EditButton.php(141): ComboStrap\EditButton::replaceAll('<section class=...')
  #4 /home/hasmotinc/public_html/wiki/lib/plugins/combo/ComboStrap/FetcherMarkup.php(804): ComboStrap\EditButton::replaceOrDeleteAll('<section class=...')
  #5 /home/hasmotinc/public_html/wiki/lib/plugins/combo/ComboStrap/TemplateForWebPage.php(598): ComboStrap\FetcherMarkup->getFetchString()
  #6 /home/hasmotinc/public_html/wiki/lib/plugins/combo/ComboStrap/TemplateForWebPage.php(162): ComboStrap\TemplateForWebPage->getModel()
  #7 /home/hasmotinc/public_html/wiki/lib/plugins/combo/ComboStrap/FetcherPage.php(154): ComboStrap\TemplateForWebPage->render()
  #8 /home/hasmotinc/public_html/wiki/lib/plugins/combo/action/docustom.php(180): ComboStrap\FetcherPage->getFetchString()
  #9 /home/hasmotinc/public_html/wiki/inc/Extension/EventHandler.php(80): action_plugin_combo_docustom->executeComboDoAction(Object(dokuwiki\Extension\Event), NULL)
  #10 /home/hasmotinc/public_html/wiki/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
  #11 /home/hasmotinc/public_html/wiki/inc/ActionRouter.php(83): dokuwiki\Extension\Event->advise_before()
  #12 /home/hasmotinc/public_html/wiki/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction('show')
  #13 /home/hasmotinc/public_html/wiki/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
  #14 /home/hasmotinc/public_html/wiki/inc/actions.php(19): dokuwiki\ActionRouter::getInstance(true)
  #15 /home/hasmotinc/public_html/wiki/doku.php(131): act_dispatch()
  #16 {main}

EVENTUALLY LEADING TO:
  #0 /home/hasmotinc/public_html/wiki/inc/parserutils.php(299): p_render_metadata('visual3d:tutori...', Array)
  #1 /home/hasmotinc/public_html/wiki/inc/common.php(262): p_get_metadata('visual3d:tutori...')
  #2 /home/hasmotinc/public_html/wiki/doku.php(101): pageinfo()
  #3 {main}

Cheers!

**Comment by gerardnico** [comment]
It depends on the page content.

To reduce the size and increase performance, we capture any xml/html node. 

This kind of message can be seen when a html node is present but not escaped with 2 percentage characters.

Ie
%%<whateverer%%

Otherwise I need the page content to check further the parsing.

Greetings !

**Comment by gerardnico** [comment]
`list_open` is a tag of dokuwiki that is created by the list `*` character. This kind of message are parsing message.

Here a test page with a second and third heading:
https://demo.combostrap.com/one-second-header-test
And it works.

**Comment by gerardnico** [comment]
I deleted the php8 array warning `EditButton.php(269) E_WARNING`
Next release, you will not see it.

**Comment by gerardnico** [comment]
For the error:
```
PDO->exec('ALTER TABLE ali...')
```
Combostrap does not have any table or migration script starting with `ali` in its [database](https://combostrap.com/analytics/combostrap-analytics-database-lafesgbz)

It seems to come from the `action_plugin_data`

**Comment by gour** [comment]
Hello,

I've the same error...after I tried to convert Pandoc User Guide (orgmode format) and exported it to Dokuwiki via Pandoc in order to check whether Dokuwiki+Combo could support such workflow as mentioned in #128 .

I'm including it here...

[example.txt](https://github.com/user-attachments/files/18618756/example.txt)

Sincerely,
Gour

**Comment by gerardnico** [comment]
I can't reproduce this error with [combostrap dokuwiki-docker](https://github.com/combostrap/dokuwiki-docker/)
The error comes from the plugin `plugins/data/action` as you can see in the stack trace.

What I see is that there is a lot of HTML element tags in your example (td, ...)
They are not supported by default, nor in dokuwiki, not yet in Combo.

I'm going to close this thread to not mix conversation.
Open a new one if you get a problem try to reproduce it with [combostrap dokuwiki-docker](https://github.com/combostrap/dokuwiki-docker/) otherwise I can't really debug it.

**Comment by gerardnico** [comment]
> example.txt

I went to investigate your example file and it has a syntax error here: `epub-subdirectory:   ''`
In dokuwiki, the `''` is equivalent to [monospaced](https://www.dokuwiki.org/wiki:syntax#basic_text_formatting) and should be close.
ie you need to have it 2 times: `''Hallo monospaced''`

Unfortunately, dokuwiki does have the notion of block and therefore continue even if there is a table or a new line in between, the rest after is therefore just monospaced and the parsing suffers from it.

If you want to try it. I made a little example

This does not work.
```
|–epub-subdirectory=""         |epub-subdirectory:   ''        |

''%%cite-method%%''
```

This works.
```
|–epub-subdirectory=""         |epub-subdirectory:   ''''        |

''%%cite-method%%''
```

**Comment by gour** [comment]
> 
> If you want to try it. I made a little example

Thank you...it does work indeed!

I've also tried with simpler examples converting Emacs' org-mode into Dokuwiki markup via pandoc and it looks good. :-)

Using DW instead of static-site-generator looks promising and with much less fiddling required... 😎
