### ISSUE TITLE
Exception after installation: Class "IntlDateFormatter" not found

### ISSUE THREAD

**Issue by knieselpriem** [ComboStrap/combo#80]
- DokuWiki: `Kaos`
- installed plugin via URI `/doku.php?id=start&do=admin&page=extension&tab=search&q=` with button `install`

Logs:
```
Error: Class "IntlDateFormatter" not found /var/www/dokuwiki/lib/plugins/combo/ComboStrap/Iso8601Date.php (187)
    #0 /var/www/dokuwiki/lib/plugins/combo/ComboStrap/ExecutionContext.php(166): ComboStrap\Iso8601Date::createFromNow()
    #1 /var/www/dokuwiki/lib/plugins/combo/ComboStrap/ExecutionContext.php(262): ComboStrap\ExecutionContext->__construct()
    #2 /var/www/dokuwiki/lib/plugins/combo/ComboStrap/ExecutionContext.php(276): ComboStrap\ExecutionContext::createBlank()
    #3 /var/www/dokuwiki/lib/plugins/combo/ComboStrap/WikiPath.php(263): ComboStrap\ExecutionContext::getActualOrCreateFromEnv()
    #4 /var/www/dokuwiki/lib/plugins/combo/ComboStrap/WikiPath.php(514): ComboStrap\WikiPath::createMarkupPathFromPath()
    #5 /var/www/dokuwiki/lib/plugins/combo/ComboStrap/MarkupPath.php(216): ComboStrap\WikiPath::createMarkupPathFromId()
    #6 /var/www/dokuwiki/lib/plugins/combo/action/lang.php(78): ComboStrap\MarkupPath::createMarkupFromId()
    #7 /var/www/dokuwiki/inc/Extension/EventHandler.php(80): action_plugin_combo_lang->load_lang()
    #8 /var/www/dokuwiki/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event()
    #9 /var/www/dokuwiki/inc/Extension/Event.php(133): dokuwiki\Extension\Event->advise_before()
    #10 /var/www/dokuwiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #11 /var/www/dokuwiki/inc/init.php(233): dokuwiki\Extension\Event::createAndTrigger()
    #12 /var/www/dokuwiki/index.php(20): require_once('...')
    #13 {main}
```

**Comment by knieselpriem** [comment]
Found the solution myself. I had to install these additional PHP extensions:

```bash
sudo apt-get install -y php-sqlite3 php-intl
``` 

This part is missing in the documentation for installing Combo!

**Comment by gerardnico** [comment]
What I mean is that there is a link to php extension 

https://combostrap.com/support/combostrap-platform-requirements-956axulc#moduleextension
